### ISSUE TITLE
Request support for boost::span

### ISSUE THREAD

**Issue by Arsennnic** [BlueBrain/HighFive#1024]
I use `boost::span` as an alternative to `std::span` since I'm limited to C++17. `boost::span` has been introduced in Boost core since [Boost-1.78](https://www.boost.org/doc/libs/1_78_0/libs/core/doc/html/core/span.html), which is a compatible implementation of `std::span`.

Would you please and the support for `boost::span`?

Alternatively, would you mind if I refer to the code in `<highfive/span.hpp>`, implement this feature by myself, and open a pull request?

**Comment by 1uc** [comment]
Thank you, nice idea. We implemented it in #1025 but since it's a very recent addition, the Boost version installed in the CI image (and I believe commonly on Ubuntu) is too old, i.e. `v71`.

Finishing the implementation would require splitting `boost.hpp`. Then setting up special CI to check against more modern versions of boost and finally make the automated tests aware of the boost version available so the can avoid testing `boost::span` iff it's not available.

**Comment by Arsennnic** [comment]
Thanks!

**Comment by 1uc** [comment]
Should be available on the main branch now.
