### ISSUE TITLE
`HighFiveConfig.cmake` should not unconditionally `add_library(HighFive ALIAS HighFive::HighFive)`

### ISSUE THREAD

**Issue by Jacobfaib** [BlueBrain/HighFive#1050]
**Bug Description**
If a project `foo` and its dependency `bar` have a diamond dependency on `HighFive`, and both export `HighFive` cmake files (as is default), then you run into the following error:
```
CMake Error at /path/to/test/install/lib/cmake/HighFive/HighFiveConfig.cmake:18 (add_library):
  add_library cannot create ALIAS target "HighFive" because another target
  with the same name already exists.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.30.5/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /path/to/test/install/lib/cmake/foo/foo-dependencies.cmake:45 (find_dependency)
  /path/to/test/install/lib/cmake/foo/foo-config.cmake:72 (include)
  ...
```
Because:
1. In `foo-config.cmake` it goes to load `bar-config.cmake`.
2. `bar-config.cmake` successfully loads and loads `HighFive`.
3. `HighFive` loads and creates its targets.
4. Now `foo-config.cmake` goes on to _also_ load `HighFive`.
5. `HighFive` now re-loads. `HighFiveTargets.cmake` is idempotent, and early-returns before re-creating `HighFive::HighFive`.
6. `HighFiveConfig.cmake` is not, and attempts to create the targets again.
7. Error.

The fix is 
```diff
diff --git a/cmake/HighFiveConfig.cmake b/cmake/HighFiveConfig.cmake
index 33ce7b7..a270d4c 100644
--- a/cmake/HighFiveConfig.cmake
+++ b/cmake/HighFiveConfig.cmake
@@ -14,6 +14,9 @@ if(HDF5_IS_PARALLEL)
   find_dependency(MPI)
   target_link_libraries(HighFive::HighFive INTERFACE MPI::MPI_C MPI::MPI_CXX)
 endif()
-
-add_library(HighFive ALIAS HighFive::HighFive)
-add_library(HighFiveInclude ALIAS HighFive::Include)
+if(NOT TARGET HighFive)
+  add_library(HighFive ALIAS HighFive::HighFive)
+endif()
+if(NOT TARGET HighFiveInclude)
+  add_library(HighFiveInclude ALIAS HighFive::Include)
+endif()
```

**Version Information**
  - HighFive: 2.9.0
  - CMake: 3.30.5

**Comment by Jacobfaib** [comment]
I suppose the 
```cmake
if(HDF5_IS_PARALLEL)
  find_dependency(MPI)
  target_link_libraries(HighFive::HighFive INTERFACE MPI::MPI_C MPI::MPI_CXX)
endif()
```
could also be skipped on the second load, but IIRC linking the same library twice is benign. In any case, cmake does not complain

**Comment by 1uc** [comment]
Thank you for reporting the issue.

**Comment by 1uc** [comment]
I tried to build a reproducer by creating a copy of the `dependent_library`:
https://github.com/BlueBrain/HighFive/tree/master/tests/cmake_integration

The two libraries that use HighFive seem to both not install anything HighFive related; and the project that uses the two dependent libraries seem to work fine. The way they're set up is that HighFive is installed (as if it where a regular library); both libraries use that copy and then the project to test the two libraries also uses the same copy.

@Jacobfaib when you encountered the issue, was HighFive vendored into the two libraries `foo` (and presumably `bar`), e.g. through
```
add_subdirectory(third_party/HighFive)
```

**Comment by Jacobfaib** [comment]
> was HighFive vendored into the two libraries foo (and presumably bar),

Hmmmm no, only one of the libraries (the main one) vendors HighFive. But the point is, I think, is that both insert a `find_dependency()` for HighFive into their `foo-targets.cmake`. 

Unfortunately I have not been able to come up with a minimal reproducer (our cmake code that is triggering this is... big), but I have been digging through all of the `<package>-config.cmake` for other third party libraries we ship. Of the 15 libraries we vendor, all of them seem to follow the practice of guarding the target creation:
```cmake
if(NOT TARGET <foo>)
  make_target(<foo>)
endif()
```
So I can only assume that this is perhaps some kind of unwritten best practice...?

**Comment by 1uc** [comment]
It does seem very sensible to guard against existence of the target.

That said, I'm not sure what happens when libraries export HighFive's `*-config.cmake`. Since, it's a header only library, it's not obvious it's correct to mix different versions into one executable. The issue is that as a header only library we're permanently (almost) violating ODR, but because all definitions are identical it doesn't count. (The linker is free to pick any which one it likes from the N identical implementations.) However, once libraries start shipping their own version of HighFive, it seems inevitable that they'll provide (slightly) different versions. The previous sentences aren't ironclad, but I think it should be reasonably easy to create an example where things break.

I've tried variations where one of the to libraries vendors HighFive and installs it along with its own code. That's still insufficient to trigger the issue, despite both libraries doing the `find_dependency(HighFive)`. I think essentially the first one sets `HighFive_FOUND` and that then prevents any other `find_dependency`s from doing too much.

When I try vendoring HighFive as part of the top-level package via `sub_directory` things start breaking in the manner you describe. Essentially the issue is that `add_subdirectory(HighFive)` clashes with the `find_dependency(HighFive)` (in the various `*-config.cmake` files). I guessing that the former creates the targets but not `HighFive_FOUND` therefore the latter still runs.

The fix you propose works and one also needs to protect the `target_link_libraries(HighFive::HighFive ...)`. However, see the longish second paragraph for why I'm still somewhat reluctant to make the change.

There's an alternative, you could try:
```
# add_subdirectory("deps/HighFive")

include(FetchContent)
FetchContent_Declare(
  HighFive
  SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/deps/HighFive"
  FIND_PACKAGE_ARGS
)
FetchContent_MakeAvailable(HighFive)
```
my current understanding is that it'll first try to `find_package(HighFive ...)` and if that fails it'll try something possibly akin to `add_subdirectory(...)` (with the provided path).

If at least one of the libraries that also vendors HighFive is a hard requirement, then there's no need to vendor HighFive in the top-level project, it can simply be picked up with a `find_package(HighFive ...)`. If the top-level package doesn't use HighFive on its own, then neither vendoring, nor `find_package(HighFive ...)` is needed, simply finding and "linking" against the libraries that use HighFive should be sufficient.
