### ISSUE TITLE
Very short syntax

### ISSUE THREAD

**Issue by tdegeus** [BlueBrain/HighFive#124]
If a user just wants to quick and accept all defaults, a very nice syntax could be:

```cpp
File file(FILE_NAME, File::ReadWrite | File::Create | File::Truncate);

std::vector<int> data(size_dataset);
// ...

file.write(DATASET_NAME, data);
```

The data-type would thereby be derived from the ``std::vector``. Similarly one could

```cpp
File file(FILE_NAME, File::ReadOnly);

std::vector<int> read_data = file.read<std::vector<int>>(DATASET_NAME);
```

which would shorten an example like [examples/read_write_vector_dataset.cpp](https://github.com/BlueBrain/HighFive/blob/master/src/examples/read_write_vector_dataset.cpp). 

*One could refine the syntax*, for example

```cpp
std::vector<int> read_data = file.readVector<int>(DATASET_NAME);
```

This would allow simpler implementation.

**Comment by henryiii** [comment]
By the way, I think you can already get a bit shorter without changes to HighFive:

```cpp
file.createDataSet<int>(DATASET_NAME, DataSpace::From(data)).write(data);
...
file.getDataSet(DATASET_NAME).read(read_data);
```

Though, I'd like a way to avoid the extra bits (`<type>`, listing `data` twice, pre-creating the output on C++11 instead of a move).

**Comment by henryiii** [comment]
We now have, with the latest master after #130 was merged:

```cpp
std::array<int, SIZE> data);
// ...

File file(FILE_NAME, File::Overwrite);

// Creates and writes to dataset with data
file.createDataSet(DATASET_NAME, data);
```

and for reading (previously possible):

```cpp
File file(FILE_NAME, File::ReadOnly);

std::array<int, SIZE> read_data;
file.getDataSet(DATASET_NAME).read(read_data);
```

Better? (also now supports 1D `std::array`s). The data now is only given once, and types are inferred. You can still get access to the DataSet to add attributes and things like that.

**Comment by hernando** [comment]
I think the current API allows a syntax which is short enough for simple use cases. Adding dataset read functions at the file level is more complicated than it seems because it would need to deal with grouping as in file.read("group/subgroup/dataset") and for consistency the same thing should be possible from the group interface. While I see the value of this addition (h5py API is similar), we don't have the bandwidth to implement this at the moment.

**Comment by tdegeus** [comment]
I like the write syntax like this. I also understand the difficulties of having a `h5py` like experience, especially because C++ does not have a clear backend like NumPy. Neither is STL sufficiently rich, nor is there a clear library that everybody uses.

**Comment by henryiii** [comment]
The issues present in the write syntax (duplicate uses of the same container, multiple listing of types) were not present in the read syntax. The only issue is the pre-creation of the type - but that can't get much better because you have to know the type at compile time.

And, the current read syntax is close to ideal if you are filling in a class's methods since those are already constructed, which I assume in real code is one of the most common uses.

Just to be clear, I'm saying the current method:

```cpp
std::array<int, SIZE> read_data;
file.getDataSet(DATASET_NAME).read(read_data);
```

would not really be made any better by a hypothetical:

```cpp
auto read_data = file.getDataSetAndRead<std::array<int, SIZE>>(DATASET_NAME, read_data);
```

And, for filling in class members, it would be worse.

**Comment by tdegeus** [comment]
@hernando I refer to the syntax added by #130 indeed.

**Comment by tdegeus** [comment]
@henryiii I see and potentially agree ;)
