### ISSUE TITLE
1D assertion failure

### ISSUE THREAD

**Issue by karjonas** [BlueBrain/HighFive#144]
Hi,

I am getting assertion failures from commit a06a59c771e7827c93ffba7cb8064a179bdda0cd:

```
braynsTestData: /home/jkarlsso/local/include/highfive/bits/H5Converter_misc.hpp:162: HighFive::details::data_converter<std::vector<_RealType>, typename std::enable_if<(std::is_same<T, typename HighFive::details::type_of_array<T>::type>::value)>::type>::data_converter(std::vector<_RealType>&, HighFive::DataSpace&) [with T = vmml::vector<4ul, float>; typename std::enable_if<(std::is_same<T, typename HighFive::details::type_of_array<T>::type>::value)>::type = void]: Assertion `is_1D(_space.getDimensions())' failed.
unknown location(0): fatal error in "render_circuit_and_compare": signal: SIGABRT (application abort requested)
```
The assertion code looks like this:

```
inline bool is_1D(const std::vector<size_t>& dims)
{
    return std::count_if(dims.begin(), dims.end(),
                         [](size_t i){ return i > 1; }) < 2;
}
```

This checks the presence of only one dimension of size 2 or greater which seems strange. I would assume it should look more like this:

```
inline bool is_1D(const std::vector<size_t>& dims)
{
    return dims.size() == 1 && dims[0] == 1;
}
```
What do you think?

**Comment by karjonas** [comment]
Maybe @henryiii or @hernando knows.

**Comment by hernando** [comment]
The code should return true for vector such as {1, 1, 1, N} because the first M-1 dimensions can be collapsed.

**Comment by hernando** [comment]
Now that I remember, I think I saw the problem before because I have some uncommitted fixed for this issue. If I remember correclty, the problem occurs with non-scalar types, which is something sort of specific to Brion, which reads directly into `std::vector<vmml::VectorX>`. The changes that I made were not sufficient to deal with non-scalar types correctly. Additional changes were necessary in Brion, but those changes have already been merged because they consisted on template specializations that are backwards compatible.
I'll submit a PR for it.

**Comment by hernando** [comment]
In fact, there's nothing to fix in HighFive. The fix could be done in Brion and it was merged weeks ago. Fixing it in HighFive would require unnecessary complications in the code to support just a single known use case that can get done with template specializations (the current solution in Brion).
