### ISSUE TITLE
Continuous integration should cover additional environments

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/HighFive#146]
HighFive should be tested against several versions of gcc and clang and also tested on both Linux and MacOS. There are opened issues with msvc, this compiler should also be tested.

See [spdlog](https://github.com/gabime/spdlog) repository that uses TravisCI for Linux/MaxOS and AppVeyor for Windows. The 2 YAML configs can almost be copy/pasted, we just have to add libhdf5 installation.

**Comment by tristan0x** [comment]
Continuous integration now provides several Linux builds and a MacOS one. Only the Windows build remains.

**Comment by ferdonline** [comment]
Dear @emmenlau @contre. I'm tagging you here since we really would like to have Windows tests in Travis and you seem to have solid knowledge there. Unfortunately our team doesn't do windows development and any attempt becomes really a pain. 
Would you mind sharing some details on how you setup your environment? If you are used to Travis even better! Any help here would be really very appreciated! Thanks

**Comment by contre** [comment]
Sorry, zero experience with Travis so I can't really provide any guidance there.

The error as reported on the PR, appears like the path export might be overwriting the entire path instead of appending. Some quick googling finds this example for a travis config https://github.com/theory/winperl-travis/blob/master/.travis.yml

**Comment by emmenlau** [comment]
Dear @ferdonline I'd like to help but our setup is quite different, we do not use conda at all and build everything from source. Since this requires a lot of scripting we use the `bash` shell from `cygwin` on Windows to orchestrate the build.
I've never seen this conda error and have no experience with it, sorry :-(

**Comment by tristan0x** [comment]
Let me share the outcome of some investigation regarding the Windows build.
Travis Windows build relies on Chocolatey package manager. HDF5 does not seem to be officially supported but I found [a recipe](https://github.com/keenbrowne/chocolatey-hdf5) that we could use or hack.
Here are some instructions from [Chocolatey documentation](https://chocolatey.org/docs/create-packages#testing-your-package) to use it.

**Comment by alkino** [comment]
I close it as, the commit is ready
