### ISSUE TITLE
Reading empty dataset works on Unix but crashes on MSVC

### ISSUE THREAD

**Issue by emmenlau** [BlueBrain/HighFive#172]
When I try to read an empty dataset, on Unix I receive correctly an empty vector. On MSVC however the same code crashes with error `Exit code 0xc0000417`.

Here is an example:
```
    const std::string vFilename = "./EmptyFile.h5";
    HighFive::File vFile(vFilename, HighFive::File::Create);
    //create unlimited empty ObjectClass table
    const HighFive::DataSpace aDataspace = HighFive::DataSpace({ 0 }, { HighFive::DataSpace::UNLIMITED });
    // Use chunking
    HighFive::DataSetCreateProps aProps;
    aProps.add(HighFive::Chunking(std::vector<hsize_t>{5}));

    // Create the dataset
    const std::string vSetName = "EmptySet";
    const HighFive::DataSet vDataSet = vFile.createDataSet<std::string>(vSetName, aDataspace, aProps);
    std::vector<std::string> vEmptySetData;
    vDataSet.read(vEmptySetData);
```

**Comment by contre** [comment]
Using your supplied code, I was able to reproduce this on my computer and found that I only saw the error when compiled in debug mode. This is likely due to the _ITERATOR_DEBUG_LEVEL macro set in debug mode. The MSVC STL has a check to make sure you're not going out of bounds on the vector when _ITERATOR_DEBUG_LEVEL is not zero.

Have you tried compiling in release mode or with the _ITERATOR_DEBUG_LEVEL set to 0?

**Comment by emmenlau** [comment]
Thanks a lot @contre for the feedback! I have recompiled my code completely with `_ITERATOR_DEBUG_LEVEL=0` but it was quite a big effort because all libraries need to have the same setting. I will now test again and let you know if it works!

**Comment by emmenlau** [comment]
Yes, this actually resolves the issue. Closing as fixed / invalid.

**Comment by drelatgithub** [comment]
Sorry for bringing this up again, but in my opinion, the following code invokes undefined behavior when `val` (which is a `std::vector<T>`) is empty, because `val[0]` accesses a nonexistent element. Therefore, I think MSVC's behavior is not incorrect.
https://github.com/BlueBrain/HighFive/blob/04793312009943e46a917ed113446b4ab1ab5379/include/highfive/bits/H5Utils.hpp#L80-L87

I'm wondering is it possible not to assign sizes of other dimensions (leave them as zeros), such that the codes look something like the following:
```c++
    static std::array<size_t, recursive_ndim> getDimensions(const type& val) {
        std::array<size_t, recursive_ndim> sizes{val.size()};
        size_t index = ndim;
        if(!val.empty()) {
            for (const auto& s: inspector<value_type>::getDimensions(val[0])) {
                sizes[index++] = s;
            }
        }
        return sizes;
    }
```
where UB is eliminated and the performance cost should be negligible. I think this is justified because since the first dimension has size zero, the rest of dimension sizes will not matter anyway (better than whatever values obtained via a UB access).

Thanks for this amazing library and please let me know what you think!

**Comment by emmenlau** [comment]
Seems reasonable?

**Comment by drelatgithub** [comment]
Thank you!
On a second thought, I find that a certain change it is going to cause is when type `T` in `std::vector<T>` has a dimension known at compile-time, such as when `T` is `std::array<U, N>`. For example, if I have an empty `std::vector<std::array<int, 3>>`, after my proposed change, the data space sizes will be `{ 0, 0 }` instead of `{ 0, 3 }`. Though, strictly speaking, `{ 0, 3 }` was the result after UB so it is not guaranteed.
Still, I think this change is acceptable, given the data has zero size in total.
Do you still think this is reasonable? If yes, I can later submit a PR for this.
