### ISSUE TITLE
CMake version compatibility

### ISSUE THREAD

**Issue by ferdonline** [BlueBrain/HighFive#283]
With release version 2.2 we might review the minimum required CMake version.
It sounds reasonable that a bare install of the HighFive headers doesn't require more than CMake 3.0, but for complete Target export we require a relatively newer version, e.g. 3.5 already avail in Ubuntu LTS 16.
A deprecation message should be issued when using CMake 3.0.

**Comment by tristan0x** [comment]
I am not sure to understand.

You want to keep `cmake_minimum_required(VERSION 3.0)` but emit a deprecation message if < 3.5 ?

I would either bump cmake_minimum_version to 3.5 or simply disable the Target export and emit a warning telling that this requires 3.5 or higher.

**Comment by ferdonline** [comment]
I was referring to the second option. We print a message informing of what has been disabled since the user doesnt have 3.5.
Besides that we must be sure everything works in 3.5.

**Comment by tdegeus** [comment]
I did some investigating for CMake 3.5. My conclusion is that it is not so much the target that is causing issues but rather the functions that add things to it (`target_link_libraries `, `target_include_directories`, `target_compile_definitions`, `target_compile_options`, ...). These functions can be avoided. E.g.

```cmake
# This is version dependent
target_compile_options(myproject::extra INTERFACE -Wall)

# This isn't
set_property(TARGET myproject::extra PROPERTY INTERFACE_COMPILE_OPTIONS -Wall)
```

References are:

* [My question of StackOverflow](https://stackoverflow.com/questions/59856505/cannot-specify-compile-options-for-imported-target).
* [A dummy project where I verified that the proposed solution indeed works with CMake 3.5](https://github.com/tdegeus/test_cmake)

I opened https://github.com/BlueBrain/HighFive/pull/272 that introduced this fix but was not yet fully correct from MPI. For now I closed it because of unresponsiveness.
