### ISSUE TITLE
Parallel HDF5 support

### ISSUE THREAD

**Issue by mrzv** [BlueBrain/HighFive#30]
README.md says that HighFive supports parallel HDF5. From looking at [HDF5 parallel tutorial](https://support.hdfgroup.org/HDF5/Tutor/parallel.html), I think HDF5 needs some information from MPI (for example, communicator) for parallel IO. But I see none of this in HDF5 code. Am I misunderstanding what you mean by supporting parallel HDF5? Or am I missing something in the code?

**Comment by adevress** [comment]
Hi Mrz,

What I mean in the README is the following point: 

- Using parallel HDF5 with the official libhdf5 cpp interface is not possible because the CPP interface is disable when the parallel HDF5 support is enabled ( on purpose ).

- Using parallel HDF5 with  HighFive is possible because HighFive is a pure Header-only interface on top of C libhdf5.

Before it was implying to pass manually the HDF5 C properties to HighFive.

I just changed that to make it easier to use in the pull request #31. 

You should have now an example example/parallel_hdf5_write_dataset.cpp in the source tree that demonstrate how to do it :)

Cheers,
Adev

**Comment by mrzv** [comment]
Brilliant! That example is very helpful. Thanks.

The example is missing a couple of things:
 * You need to call `MPI_Finalize` at the end, otherwise MPI complains when the code exits.
 * You need to adjust `CMakeLists.txt` to `find_package(MPI)` and actually link against MPI (plus add it to the include directory paths, in case it's in a non-standard location). Otherwise, the code doesn't build at least on some platforms.

**Comment by adevress** [comment]
> You need to call MPI_Finalize at the end, otherwise MPI complains when the code exits.

Thx, I will fix that

> You need to adjust CMakeLists.txt to find_package(MPI) and actually link against MPI (plus add it to the include directory paths, in case it's in a non-standard location). Otherwise, the code doesn't build at least on some platforms.

You don't have this problem if you compile with mpicc / mpic++ :)

**Comment by mrzv** [comment]
> You don't have this problem if you compile with mpicc / mpic++ :)

Sure, but that's not what CMake picks up by default.

**Comment by adevress** [comment]
Ok, it should be fixed with the last merge
