### ISSUE TITLE
Can I get the path to a DataSet?

### ISSUE THREAD

**Issue by tdegeus** [BlueBrain/HighFive#314]
Can I get the path to a DataSet from a `HighFive::DataSet` object?

**Comment by alkino** [comment]
I think no because it is possible to have several path to the same DataSet.

**Comment by tdegeus** [comment]
Make senses. I guess the only possible way would be if a `HighFive::DataSet` instance would keep memory of the path with which is was called. But I see no urgent reason for it.

**Comment by KerimMatlab** [comment]
I think this could be done via [H5I_GET_NAME(obj_id, name, size)](https://portal.hdfgroup.org/display/HDF5/H5I_GET_NAME)

> I think no because it is possible to have several path to the same DataSet.

this is said in documentation that folows the link above but at least one path is returned. Ttis may be enough.

I do not provide any code for this task because I'am beginner at programming (it is only few months that I work with C/C++). It is hard to change the source code without knowing the core of library.

**Comment by alkino** [comment]
This is the right function to do it, thanks I will give a try

**Comment by tdegeus** [comment]
Thanks @KerimMatlab ! And thanks @alkino for giving it a try !

**Comment by KerimMatlab** [comment]
@tdegeus I added this functionality to the [pull request ](https://github.com/BlueBrain/HighFive/pull/346)
#314

**Comment by matz-e** [comment]
Closed in #314.
