### ISSUE TITLE
Proposing to add some meaningul changes to library

### ISSUE THREAD

**Issue by kerim371** [BlueBrain/HighFive#406]
Hi,

My project greatly depends on HDF5, so I work a lot with HighFive and HDF5. The problem is that when I try to contribute to HighFive it may take too much time approve it, so few weeks ago I've cloned HighFive and made much of noticeable changes (this package is called HFGt and here is the[ link to google drive](https://drive.google.com/file/d/1kLxs-ncZZVzKAylhUOEHa-xiAgxVc0VA/view?usp=sharing)). I would divide those changes in two groups: changes that I would propose to accept in HighFive and changes for my comfortability (you don't have to accept the latest as it something like a simplification of cmake structure, change BOOST for a GOOGLE test etc).
The changes I would like to share:
1) Allow users to increase/decrease reference count when doing such operations like getId() or getFileId() or File::FromId(). That changes the philosophy of HighFive where each ID is decreased in object's destructor (when object is not needed) and thus that simplifies the usage of HighFive. But in the same time you may want to have two independent objects with the same ID and when one is destructed the other one would work. I'm going to try to make python bindings for HighFive (I have not much experience of that but I need it and thus I think I will do that) and here this getId(bool increaseRefCount) may play a noticeable role when transferring ID between python H5PY and HighFive.
2) I added Soft and External link. That means you may have few links pointing to the same object. In my library I need this in situation where there are few datasets (or groups) in group and I need to set active one of them without copying data. In the future I think I would implement external dataset (when you have a binary outside of HDF5 container and you want to work with this binary as with dataset). 
3) I changed the idea of property list. It used to be a class that accept any property that follows some condition and those properties are added via propList.add(property). This is difficult to use because you have to always remember what properties are common for the current object. So I changed this idea and made different classes for different propertyLists. For example there are GroupCreatePropertyList, DatasetCreatePropertyList, GroupAccessPropertyList and other and each of them have its own properties. This make more coding for HighFive developper but it also makes easier to use properties.
4) When working with HDF5 you are allowed to set different properties when working with different HDF5 functions. In HighFive some of those properties are set as H5P_DEFAULT. I changed it and user can always set the properties he needs in most of the ti,e. Also there is property that creates intermediate groups when creating new object. In HighFive now it is implemented something like createGroup(bool createIntermediateGroup = true) (and this was not implemented when creating datasets) and with new approach this is done by default in LinkCreationPropertyList (names may spell something different I don't remember).

Most of those changes are tested in unit tests.
I think there should not much problems to launch it, please look at this package.

So as I need HighFive I would like to implement some features and I don't want to create my own fork wich is fully based on HighFive. But to do that I need to closely interact with approved HighFive person that could give me feedback and accept/deny changes pretty fast. I understand that most of you are busy but maybe there is someone who is interested in that.

**Comment by matz-e** [comment]
Hi @kerim371 ,

I'm sorry about the frustrations that arise working with us! HighFive is an essential utility library for us, but we also often don't have the resources to follow up in detail. Some of the issues you mention are hard for us to gauge, since they don't arise in our use-case.

As customary with open source, you're free to build upon HighFive and customize it to your needs. We do the same with other projects, and provide feedback / patches where we deem it appropriate. We're currently discussing the status of HighFive internally, too.

For your proposals, I can try to give you a bit of input based on *my* opinion.

0. Replacing the Boost unit tests is actually something I would favor. We have been using the Catch framework a lot for this, and I would give that preference over Google libraries.
1. I'm not sure that we would want to open the reference count up within the API. If there was a strong use-case and a working demonstration of the coupling between h5py and HighFive, we could discuss this more. There is always going to be hesitation to add API features that are of a more experimental nature.
2. Seems like a no-brainer and a very welcome feature.
3. (and 4) I agree that the property list handling is something that could be improved. Working on I/O performance, I came across some issues here, too, and resulted to changing the HighFive internals locally. I'll probably have to ping someone with more experience on this.

**Comment by kerim371** [comment]
@matz-e thank you for feedback

I think after merging my existing PR (with aim to not mess repositories) I will fork HighFive and try to develop it. I f I have success with python bindings I will notify the community and we will think what features HighFive should include and how to merge them in main fork.

**Comment by ferdonline** [comment]
Individual issues were created to replace this. Please see comments in PR #400 and issue #418 and #419
