### ISSUE TITLE
Support for Armadillo?

### ISSUE THREAD

**Issue by berquist** [BlueBrain/HighFive#482]
Armadillo has been brought up once in #3.  For my own usage I've written an [interface](https://github.com/berquist/eg/blob/ec0eb38f293f6aefc55ebfc4ccd3f9ccbd92ac60/cpp/highfive/highfive_arma.hpp) that needs cleaning up but does work, though I haven't benchmarked it yet.

The annoying thing about Armadillo is dealing with the column-major layout. Their own HDF5 interface writes out as though the underlying memory is row-major, so the file isn't trivially usable from...any other code, really. This interface does the obvious right thing for row vectors, column vectors, and matrices in terms of shapes. Cubes are a little weird (from [docs](http://arma.sourceforge.net/docs.html#Cube)):

> Cube data is stored as a set of slices (matrices) stored contiguously within memory. Within each slice, elements are stored with column-major ordering (ie. column by column)

Because iterating over the slice index is typical, I decided to put the slice index first.

Is this something the project would be interested in adding?

**Comment by tdegeus** [comment]
I'm not interested in adding it, but would be happy to review. The H5Easy API is a good place to add this first. There are already many templates: Eigen, xtensor, ImageCV

**Comment by pramodk** [comment]
@berquist: if you have working draft, please open a pull request and someone from our side would be happy to review and provide feedback. Thanks in advance!

**Comment by berquist** [comment]
#586 completely changed the interface in `H5Converter_misc.hpp`.  I had written `data_converter`s and `inspector`s for each class.  Do I switch from `data_converter` to `Reader` and `Writer`, or is it something else?

**Comment by 1uc** [comment]
@berquist Most of the code has been concentrated in the `inspector<T>`. Hopefully the code for `boost::multi_array` is helpful, see
https://github.com/BlueBrain/HighFive/blob/64b7ad9a9cca566de1103ac74abab710b6f928cb/include/highfive/bits/H5Inspector_misc.hpp#L697

I think you'd move most of you code into the `inspector` and leave the `Reader` and `Writer` alone. In order to improve the way we handle strings, we'll probably end up reworking the `Reader` and `Writer`, see #744 for a sketch of what we intend to do; and if it affects you.
