### ISSUE TITLE
How to create node-dependent group or dataset parallelly  for parallel file systems.?

### ISSUE THREAD

**Issue by luohao0925** [BlueBrain/HighFive#506]
I want to create node-dependent group or dataset using the parallel HDF5. However, the example is not provided in `src/examples`. So, I would like to know if this feature is supported and how to use it. Thank you!

**Comment by matz-e** [comment]
Do you have a few more details about what you are trying to do?

If you open one file across several processes, IIRC, all processes have to create the structure of the HDF5 file together. See also the comment on top of here: https://portal.hdfgroup.org/pages/viewpage.action?pageId=48809645

> All processes have to call H5Dcreate() to create a dataset, even if the dataset will be accessed by one process.

Hope this helps?

**Comment by luohao0925** [comment]
The comment really helps! Thank you very much!

**Comment by luohao0925** [comment]
When I follow the comment on the link and run the following code 
```
int main(int argc, char** argv) {
  int mpi_rank, mpi_size;

  // initialize MPI
  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &mpi_size);
  MPI_Comm_rank(MPI_COMM_WORLD, &mpi_rank);

  using namespace HighFive;
  try {

    // open a new file with the MPI IO driver for parallel Read/Write
    File file(FILE_NAME, File::ReadWrite | File::Create | File::Truncate,
              MPIOFileDriver(MPI_COMM_WORLD, MPI_INFO_NULL));
    for(int i=0 ; i < mpi_size; i++) {
      char dataSetName[256];
      sprintf(dataSetName, "a%d", i + 1);
      printf("Creating dataset %s ... \n", dataSetName);

      file.createDataSet(dataSetName, mpi_rank);
    }

  } catch (Exception& err) {
    // catch and print any HDF5 error
    std::cerr << err.what() << std::endl;
    MPI_Abort(MPI_COMM_WORLD, 1);
  }

  MPI_Finalize();
  return 0; // successfully terminated
}
```
It did create  n datasets, where n is the number of processes in the communicator. However, the data in some dataset seems to be uncorrect! The data in dataset a4 is expected to be 4 instead 1. I don't know how this happens.
![dataset](https://user-images.githubusercontent.com/52783667/156118355-4a38c8ff-0f44-457e-98d7-418870193709.png)

**Comment by luohao0925** [comment]
I tried to add a judgement after creating a dataset, like
```
    for(int i=0 ; i < mpi_size; i++) {
      char dataSetName[256];
      sprintf(dataSetName, "a%d", i + 1);
      printf("Creating dataset %s ... \n", dataSetName);

      const DataSetCreateProps createProps;
      const DataSetAccessProps accessProps;
      DataSet set = file.createDataSet(
          dataSetName, DataSpace::From(data),
          AtomicType<typename details::type_of_array<int>::type>(), createProps,
          accessProps);
      if (i == mpi_rank) {
        set.write(data);
      }
```
it seems to work. I want to know whether my approach is desirable!

I also found out that when the data to be written in dataset in different process has different length, the code will get stuck, for examples: 
```
std::vector<int> data(mpi_rank, 0);
```

**Comment by sergiorg-hpc** [comment]
Nice to meet you @luohao0925 and great work! Just to clarify and adding to @matz-e's comments, I believe that using multiple processes on a shared file can lead to file consistency issues, so as a rule of thumb, be always extremely careful. For instance, the following snippet from your example could lead to deadlocks when you set `H5FD_MPIO_COLLECTIVE` in the file property list:

```C
...
    for(int i=0 ; i < mpi_size; i++) {
        ...
        DataSet set = file.createDataSet(...);
        ...
        if (i == mpi_rank) {
            set.write(data);
        }
    }
...
```

If I'm not mistaken (and, please, forgive me if I'm wrong), here it should **not** be a problem because you create the datasets collectively, and then you chose to individually assign different processes to write into different datasets. However, creating a dataset is a collective operation, meaning that all the processes minus one have to wait in the `file.createDataSet(...)` operation of the next iteration until the process writing in the previous iteration is done. And the same for the next iterations, if it makes sense.

Therefore, my only observation would be to try to do this in two separate loops. First, you create the datasets one by one with all the processes (i.e., collective operation in `MPI_COMM_WORLD`). Then, you write the data separately on each of the datasets (i.e., individual I/O affecting only part of the processes). If at some point you would like to use `H5FD_MPIO_COLLECTIVE` for some reason, keep in mind that all the processes must then call `write()`, whether they write something or not, but this is for future work. For now, I think that should work!

**Comment by luohao0925** [comment]
I met another problem! When I tried to create node-dependent group, it failed. The following code is expected to create two groups "g1 and g2" when two processes are utilized:
```
...
    group = file.createGroup(...);
    for(int i=0 ; i < mpi_size; i++) {
        ...
        DataSet set = group.createDataSet(...);
        ...
        if (i == mpi_rank) {
            set.write(data);
        }
    }
...
```
<img width="235" alt="截屏2022-05-13 16 20 39" src="https://user-images.githubusercontent.com/52783667/168242043-33fd3f2a-d8cb-4380-b9d4-50fd4b478ec6.png">

**Comment by 1uc** [comment]
Sorry for replying very late, to the point that it's of no use. Therefore, only a short explanation for other finding this entry:

The most likely explanation is that since you're creating a different group for each MPI rank, when you're creating new datasets, that's not a collective operation, i.e. MPI rank 0 will try to create `g0/a0` and then `g0/a1`. While at the same time MPI rank 1 is trying to create `g1/a0` and `g1/a1`. Hence MPI rank 1 doesn't know about `g0/a?` and conversely MPI rank 0 doesn't know about `g1/a?`.
