### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by mbadikyan** [BlueBrain/HighFive#734]
**Describe the bug**
Trying to compile H5Easy with the following command in my command line:

**To Reproduce**
`$ g++ -c -I HighFive/include/ read_ray_data.cpp -lhdf5`

**Expected behavior**
It should create a compiled object, correct? But I get the following error:

**Stacktrace**

In file included from HighFive/include/highfive/H5FileDriver.hpp:11:0,
                 from HighFive/include/highfive/H5File.hpp:13,
                 from HighFive/include/highfive/H5Easy.hpp:57,
                 from read_ray_data.cpp:9:
HighFive/include/highfive/H5PropertyList.hpp:13:10: fatal error: H5Ppublic.h: No such file or directory
 #include <H5Ppublic.h>
          ^~~~~~~~~~~~~
compilation terminated.

**Desktop (please complete the following information):**
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by 1uc** [comment]
The header `H5Ppublic.h` belongs to HDF5. Hence, the compiler is complaining that it can't find HDF5. Check if HDF5 is installed, if yes, you need to add the appropriate `-I ${HDF5_DIR}/include` and `-L ${HDF5_DIR}/lib`.

The common solution to these types of issues is to use CMake.

**Comment by mbadikyan** [comment]
Apologies, I'm new to C++. Could you explain what kind of object `hdf5` is in your compilation statement: 
`c++ -o program -I/path/to/highfive/include source.cpp  -lhdf5` ? 

Is this a compiled object containing all the needed code from HDF5? 

Thank you.

**Comment by mbadikyan** [comment]
I do have the HDF5 library - in folder `hdf5` in the same directory as `HighFive`. I ran the following command: 

`$ g++ -c read_ray_data.cpp -I HighFive/include/ -I hdf5/1.10.0/include/ -L hdf5/1.10.0/lib/`

but it gives me the following error:

`In file included from hdf5/1.10.0/include/H5Ppublic.h:26:0,
                 from HighFive/include/highfive/H5PropertyList.hpp:13,
                 from HighFive/include/highfive/H5FileDriver.hpp:11,
                 from HighFive/include/highfive/H5File.hpp:13,
                 from HighFive/include/highfive/H5Easy.hpp:57,
                 from read_ray_data.cpp:9:
hdf5/1.10.0/include/H5public.h:171:19: error: conflicting declaration ‘typedef long long int ssize_t’
 typedef long long ssize_t;
                   ^~~~~~~
In file included from /usr/include/stdlib.h:394:0,
                 from /usr/include/c++/7/cstdlib:75,
                 from /usr/include/c++/7/ext/string_conversions.h:41,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from HighFive/include/highfive/H5Easy.hpp:20,
                 from read_ray_data.cpp:9:
/usr/include/x86_64-linux-gnu/sys/types.h:109:19: note: previous declaration as ‘typedef __ssize_t ssize_t’
 typedef __ssize_t ssize_t;
                   ^~~~~~~`

**Comment by mbadikyan** [comment]
I got the files from a coworker. I see, how would you suggest making HDF5 accessible to HighFive?

**Comment by 1uc** [comment]
Okay, that explains the error. The manual process of installing a C or C++ library is to first obtain the sources, then configure and compile the sources, then install the resulting `lib*.so` and header files. It sounds like you only performed the first step.

The common way to automate the process of installing libraries on Linux is to use a package manager. On Ubuntu it's apt, you'll find documentation online of how to install packages. Since you're installing HDF5 for development purposes, you'll need to make sure it includes the header files. Some distributions put the headers into a separate package, often called `*-dev` or `*-devel`.

There are situations, e.g. lack of root permissions or restriction by ones employer, where one might not be able to or not want to use the system package manager. There's alternatives, I'll leave it to you to pick one that's suitable.

I can't really help you with this since it's purely a user error and not related to HighFive or HDF5. The knowledge you're missing is how to compile sources that have dependencies. You'll find good resources online that can help you understand the process.

I'd recommend you start simple; and if simple doesn't work, continue with something simpler. You could start by compiling some of the simplest examples from the HDF5 webpage docs.hdf5group.org. If that works you know you've installed HDF5 correctly. Then you can try one of our examples, pick one that looks simple (i.e. has few lines of code), depending on the compiler version the only difference would be that you need to add `-I HighFive/include` to the `g++` invocation that worked for the HDF5 example. If that works too you should be set to tackle your current task.

**Comment by 1uc** [comment]
Hey @mbadikyan I hope you've been able to install HDF5 and use HighFive by now. I've found some time to put together a beginners guide on the steps required to go from an empty directory to using HighFive in a project. If you're interested, you can find it here:
https://github.com/BlueBrain/HighFive/blob/1uc/improved-installation-guide/doc/installation.md

I hope that eventually it'll get added to the documentation. Note that I've tested the tricky commands, but some of the "easier" ones have not been copy-pasted from the commandline and therefore might be slightly wrong. If you do read it and have any comments, I'd like to hear them, especially if something isn't clear or missing.
