### ISSUE TITLE
configure looks for libhdf5, but then binaries aren't linked with it

### ISSUE THREAD

**Issue by yurivict** [BlueBrain/HighFive#839]
Version: 2.7.1
FreeBSD 13.2

**Comment by 1uc** [comment]
Thank you for reporting the issue. Unfortunately, it's too short for us to understand exactly what's going wrong.

We have CI for exactly this purpose; and it ran without error recently:
https://github.com/BlueBrain/HighFive/actions/runs/6729142463/job/18289533151#step:7:329

The `CMakeLists.txt` is simply (and doesn't require additional linking to HDF5):
https://github.com/BlueBrain/HighFive/blob/88fcc898970f93a63be8e25760d6b9f33589690f/tests/test_project/CMakeLists.txt#L21-L25

Unfortunately, I'm unable to help without further information and am therefore closing the issue. Feel free to reopen the ticket with enough information so that we have a chance at helping you.

**Comment by yurivict** [comment]
> Unfortunately, I'm unable to help without further information and am therefore closing the issue.


Configure looks for libhdf5 and finds it.
Then no built binaries are linked with it.

Could you please let me know what other information do you need?
Does your CI verify that libhdf5.so is linked to binaries?

**Comment by alkino** [comment]
Examples are linked with `libhdf5`. `HighFive` is a pure header library.
