### ISSUE TITLE
Support for fixed-length strings

### ISSUE THREAD

**Issue by dbichko** [BlueBrain/HighFive#94]
Hi,

I am trying to read a dataset with this type:

```C++
DATATYPE H5T_STRING {
  STRSIZE 50;
  STRPAD H5T_STR_NULLPAD;
  CSET H5T_CSET_ASCII;
  CTYPE H5T_C_S1;
}
```
Glancing at `AtomicType<std::string>::AtomicType()` it seems that only variable-length strings are expected.

Is this something that can be supported in the future?

**Comment by adevress** [comment]
Hi dbichko,

yes it will be. This is will be implemented at the same time that the support for UTF-8 / ASCII transparent mapping of #9

**Comment by mfouesneau** [comment]
Is there an example on how to read an array of string? I always get errors asking me to use FixedStringArray (or raw arrays) but the data are variable-length strings.

I cannot find a working example. I'm happy to have low-level digging.

**Comment by JATC1024** [comment]
Is there any updates on this?

**Comment by pramodk** [comment]
Any examples added in #277 help you @JATC1024 ?

**Comment by JATC1024** [comment]
Thanks for responding @pramodk 
I can read fixed-length strings using something like
```
HighFive::FixedLenStringArray<N> strs;
dset.read(strs);
```

However, based on what I understand, N must be a constant at compile time. Since I want to do this automatically for many different datasets, I cannot fix N as a constant literal.

Are there any cheat sheets about loading variable-length and fixed-length strings arrays? I am trying to do something like:
```
dset = file.getDataset("something");
if (dset.getDataType().isFixedLenStr()) {
    // Read fixed-length strings here. Don't know how though
} else {
    dset.read(data);
}
```
